# permissions for end users to view platformconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: platformconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: platform-config-operator
    app.kubernetes.io/part-of: platform-config-operator
    app.kubernetes.io/managed-by: kustomize
  name: platformconfig-viewer-role
rules:
- apiGroups:
  - capabilities.platform.tbd.io
  resources:
  - platformconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - capabilities.platform.tbd.io
  resources:
  - platformconfigs/status
  verbs:
  - get
