# permissions for end users to view platformoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: platformoperators-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: platform-config-operator
    app.kubernetes.io/part-of: platform-config-operator
    app.kubernetes.io/managed-by: kustomize
  name: platformoperators-viewer-role
rules:
- apiGroups:
  - deploy.platform.tbd.io
  resources:
  - platformoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - deploy.platform.tbd.io
  resources:
  - platformoperators/status
  verbs:
  - get
