# permissions for end users to edit platformconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: platform-config-operator
    app.kubernetes.io/managed-by: kustomize
  name: deploy-platformconfig-editor-role
rules:
- apiGroups:
  - deploy.platform.tbd.io
  resources:
  - platformconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deploy.platform.tbd.io
  resources:
  - platformconfigs/status
  verbs:
  - get
