# permissions for end users to edit platformoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: platform-config-operator
    app.kubernetes.io/managed-by: kustomize
  name: deploy-platformoperators-editor-role
rules:
- apiGroups:
  - deploy.platform.tbd.io
  resources:
  - platformoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deploy.platform.tbd.io
  resources:
  - platformoperators/status
  verbs:
  - get
