---
apiVersion: certificates.platform.tbd.io/v1alpha1
kind: TrustManager
metadata:
  name: config
  labels:
    capabilities.tbd.io/capability: platform-config
    capabilities.tbd.io/version: v0.0.1
    capabilities.tbd.io/platform-version: unstable
    app.kubernetes.io/version: unstable
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/managed-by: platform-config-operator
  annotations:
    operator-builder.nukleros.io/ready-path: .status.created
    operator-builder.nukleros.io/ready-value: "true"
spec:
  namespace: tbd-certificates-system # +operator-builder:field:name=platform.certificates.namespace,default="tbd-certificates-system",type=string
  controller:
    replicas: 2
    image: quay.io/jetstack/trust-manager:v0.9.2
    resources:
      requests:
        cpu: 25m
        memory: 32Mi
      limits:
        memory: 64Mi
